apiVersion: apps/v1
kind: Deployment
metadata:
  name: xas-controller
  namespace: default
  labels:
    app: xas-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xas-controller
  template:
    metadata:
      labels:
        app: xas-controller
    spec:
      containers:
        - name: controller
          image: xas-controller:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
