apiVersion: xas.io/v1
kind: MetricProviderClass
metadata:
  name: dynatrace
spec:
  type: Dynatrace
  config:
    # URL to Dynatrace environment (e.g. https://<env-id>.live.dynatrace.com) or mock VM
    endpoint: "http://34.140.132.84:8080"
    # Kubernetes secret containing the 'api-token' key
    apiTokenSecretRef: "dynatrace-token"
